import * as wellKnownChains from "polkadot-api/chains"
import { ChainId, ChainIdRelay, TChain } from "../../chains/types"

type chainDefinition = {
  network: ChainIdRelay
  smoldot: string | null
  info: TChain
}

export const WellKnownChains: Record<ChainId, chainDefinition> = {
  polkadot: {
    network: "polkadot",
    smoldot: wellKnownChains.polkadot,
    info: {
      id: "polkadot",
      name: "Polkadot",
      wsUrl: [
        "wss://rpc.ibp.network/polkadot",
        "wss://polkadot-rpc.dwellir.com",
        "wss://rpc.dotters.network/polkadot",
        "wss://polkadot-rpc-tn.dwellir.com",
        "wss://polkadot-rpc.publicnode.com",
        "wss://polkadot-public-rpc.blockops.network/ws",
        "wss://rpc-polkadot.luckyfriday.io",
        "wss://rockx-dot.w3node.com/polka-public-dot/ws",
        "wss://dot-rpc.stakeworld.io",
      ],
      paraId: null,
      stableTokenId: null,
    },
  },
  pah: {
    network: "polkadot",
    smoldot: wellKnownChains.polkadot_asset_hub,
    info: {
      id: "pah",
      name: "Asset Hub",
      wsUrl: [
        "wss://sys.ibp.network/statemint",
        "wss://sys.dotters.network/statemint",
        "wss://sys.ibp.network/asset-hub-polkadot",
        "wss://sys.dotters.network/asset-hub-polkadot",
        "wss://asset-hub-polkadot-rpc.dwellir.com",
        "wss://statemint-rpc-tn.dwellir.com",
        "wss://rpc-asset-hub-polkadot.luckyfriday.io",
        "wss://polkadot-asset-hub-rpc.polkadot.io",
        "wss://dot-rpc.stakeworld.io/assethub",
        "wss://statemint-rpc.dwellir.com",
      ],
      paraId: 1000,
      stableTokenId: null,
    },
  },
  pbh: {
    network: "polkadot",
    smoldot: wellKnownChains.polkadot_bridge_hub,
    info: {
      id: "pbh",
      name: "Bridge Hub",
      wsUrl: [
        "wss://bridge-hub-polkadot-rpc.dwellir.com",
        "wss://polkadot-bridge-hub-rpc-tn.dwellir.com",
        "wss://sys.ibp.network/bridgehub-polkadot",
        "wss://bridge-hub-polkadot.dotters.network",
        "wss://rpc-bridge-hub-polkadot.luckyfriday.io",
        "wss://bridgehub-polkadot.api.onfinality.io/public-ws",
        "wss://polkadot-bridge-hub-rpc.polkadot.io",
        "wss://bridgehub-polkadot.public.curie.radiumblock.co/ws",
        "wss://dot-rpc.stakeworld.io/bridgehub",
      ],
      paraId: 1002,
      stableTokenId: null,
    },
  },
  pcl: {
    network: "polkadot",
    smoldot: wellKnownChains.polkadot_collectives,
    info: {
      id: "pcl",
      name: "Collectives",
      wsUrl: [
        "wss://collectives-polkadot-rpc.dwellir.com",
        "wss://polkadot-collectives-rpc-tn.dwellir.com",
        "wss://sys.ibp.network/collectives-polkadot",
        "wss://collectives-polkadot.dotters.network",
        "wss://rpc-collectives-polkadot.luckyfriday.io",
        "wss://collectives.api.onfinality.io/public-ws",
        "wss://polkadot-collectives-rpc.polkadot.io",
        "wss://collectives.public.curie.radiumblock.co/ws",
      ],
      paraId: 1001,
      stableTokenId: null,
    },
  },
  pct: {
    network: "polkadot",
    smoldot: wellKnownChains.polkadot_coretime,
    info: {
      id: "pct",
      name: "Coretime",
      wsUrl: [
        "wss://sys.ibp.network/coretime-polkadot",
        "wss://coretime-polkadot.dotters.network",
        "wss://rpc-coretime-polkadot.luckyfriday.io",
        "wss://polkadot-coretime-rpc.polkadot.io",
      ],
      paraId: 1005,
      stableTokenId: null,
    },
  },
  ppl: {
    network: "polkadot",
    smoldot: wellKnownChains.polkadot_people,
    info: {
      id: "ppl",
      name: "People",
      wsUrl: [
        "wss://sys.ibp.network/people-polkadot",
        "wss://people-polkadot.dotters.network",
        "wss://rpc-people-polkadot.luckyfriday.io",
        "wss://polkadot-people-rpc.polkadot.io",
        "wss://people-polkadot.public.curie.radiumblock.co/ws",
      ],
      paraId: 1004,
      stableTokenId: null,
    },
  },
  kusama: {
    network: "kusama",
    smoldot: wellKnownChains.ksmcc3,
    info: {
      id: "kusama",
      name: "Kusama",
      wsUrl: [
        "wss://kusama-rpc.polkadot.io",
        "wss://rpc.ibp.network/kusama",
        "wss://rpc.dotters.network/kusama",
        "wss://1rpc.io/ksm",
        "wss://kusama-rpc.dwellir.com",
        "wss://kusama-rpc-tn.dwellir.com",
        "wss://kusama-rpc.publicnode.com",
        "wss://rpc-kusama.luckyfriday.io",
        "wss://rockx-ksm.w3node.com/polka-public-ksm/ws",
        "wss://ksm-rpc.stakeworld.io",
      ],
      paraId: null,
      stableTokenId: null,
    },
  },
  kah: {
    network: "kusama",
    smoldot: wellKnownChains.ksmcc3_asset_hub,
    info: {
      id: "kah",
      name: "Asset Hub",
      wsUrl: [
        "wss://sys.ibp.network/statemine",
        "wss://kusama-asset-hub-rpc.polkadot.io",
        "wss://sys.dotters.network/statemine",
        "wss://asset-hub-kusama-rpc.dwellir.com",
        "wss://statemine-rpc-tn.dwellir.com",
        "wss://rpc-asset-hub-kusama.luckyfriday.io",
        "wss://ksm-rpc.stakeworld.io/assethub",
      ],
      paraId: 1000,
      stableTokenId: null,
    },
  },
  kbh: {
    network: "kusama",
    smoldot: wellKnownChains.ksmcc3_bridge_hub,
    info: {
      id: "kbh",
      name: "Bridge Hub",
      wsUrl: [
        "wss://bridge-hub-kusama-rpc.dwellir.com",
        "wss://kusama-bridge-hub-rpc-tn.dwellir.com",
        "wss://sys.ibp.network/bridgehub-kusama",
        "wss://bridge-hub-kusama.dotters.network",
        "wss://rpc-bridge-hub-kusama.luckyfriday.io",
        "wss://bridgehub-kusama.api.onfinality.io/public-ws",
        "wss://kusama-bridge-hub-rpc.polkadot.io",
        "wss://bridgehub-kusama.public.curie.radiumblock.co/ws",
        "wss://ksm-rpc.stakeworld.io/bridgehub",
      ],
      paraId: 1002,
      stableTokenId: null,
    },
  },
  kct: {
    network: "kusama",
    smoldot: null,
    info: {
      id: "kct",
      name: "Coretime",
      wsUrl: [
        "wss://coretime-kusama-rpc.dwellir.com",
        "wss://sys.ibp.network/coretime-kusama",
        "wss://coretime-kusama.dotters.network",
        "wss://rpc-coretime-kusama.luckyfriday.io",
        "wss://kusama-coretime-rpc.polkadot.io",
        "wss://ksm-rpc.stakeworld.io/coretime",
      ],
      paraId: 1005,
      stableTokenId: null,
    },
  },
  kpl: {
    network: "kusama",
    smoldot: wellKnownChains.ksmcc3_people,
    info: {
      id: "kpl",
      name: "People",
      wsUrl: [
        "wss://people-kusama-rpc.n.dwellir.com",
        "wss://sys.ibp.network/people-kusama",
        "wss://people-kusama.dotters.network",
        "wss://rpc-people-kusama.luckyfriday.io",
        "wss://kusama-people-rpc.polkadot.io",
        "wss://ksm-rpc.stakeworld.io/people",
      ],
      paraId: 1004,
      stableTokenId: null,
    },
  },
  westend: {
    network: "westend",
    smoldot: wellKnownChains.westend2,
    info: {
      id: "westend",
      name: "Westend",
      wsUrl: [
        "wss://rpc.ibp.network/westend",
        "wss://rpc.dotters.network/westend",
        "wss://westend-rpc.dwellir.com",
        "wss://westend-rpc-tn.dwellir.com",
        "wss://westend-rpc.polkadot.io",
      ],
      paraId: null,
      stableTokenId: null,
    },
  },
  wah: {
    network: "westend",
    smoldot: wellKnownChains.westend2_asset_hub,
    info: {
      id: "wah",
      name: "Asset Hub",
      wsUrl: [
        "wss://sys.ibp.network/westmint",
        "wss://sys.dotters.network/westmint",
        "wss://asset-hub-westend-rpc.dwellir.com",
        "wss://westmint-rpc-tn.dwellir.com",
        "wss://westend-asset-hub-rpc.polkadot.io",
      ],
      paraId: 1000,
      stableTokenId: null,
    },
  },
  wbh: {
    network: "westend",
    smoldot: wellKnownChains.westend2_bridge_hub,
    info: {
      id: "wbh",
      name: "Bridge Hub",
      wsUrl: [
        "wss://bridge-hub-westend-rpc.dwellir.com",
        "wss://westend-bridge-hub-rpc-tn.dwellir.com",
        "wss://sys.ibp.network/bridgehub-westend",
        "wss://bridge-hub-westend.dotters.network",
        "wss://bridgehub-westend.api.onfinality.io/public-ws",
        "wss://westend-bridge-hub-rpc.polkadot.io",
      ],
      paraId: 1002,
      stableTokenId: null,
    },
  },
  wcl: {
    network: "westend",
    smoldot: wellKnownChains.westend2_collectives,
    info: {
      id: "wcl",
      name: "Collectives",
      wsUrl: [
        "wss://collectives-westend-rpc.dwellir.com",
        "wss://westend-collectives-rpc-tn.dwellir.com",
        "wss://sys.ibp.network/collectives-westend",
        "wss://collectives-westend.dotters.network",
        "wss://westend-collectives-rpc.polkadot.io",
      ],
      paraId: 1001,
      stableTokenId: null,
    },
  },
  wpl: {
    network: "westend",
    smoldot: wellKnownChains.westend2_people,
    info: {
      id: "wpl",
      name: "People",
      wsUrl: [
        "wss://people-westend-rpc.n.dwellir.com",
        "wss://sys.ibp.network/people-westend",
        "wss://people-westend.dotters.network",
        "wss://westend-people-rpc.polkadot.io",
      ],
      paraId: 1004,
      stableTokenId: null,
    },
  },
  wct: {
    network: "westend",
    smoldot: null,
    info: {
      id: "wct",
      name: "Coretime",
      wsUrl: [
        "wss://coretime-westend-rpc.n.dwellir.com",
        "wss://sys.ibp.network/coretime-westend",
        "wss://coretime-westend.dotters.network",
        "wss://westend-coretime-rpc.polkadot.io",
      ],
      paraId: 1005,
      stableTokenId: null,
    },
  },
}
